In [1]:
import numpy as np

In [2]:
# sigmoid function 
def nonlin(x, deriv=False):
    if(deriv==True): # Return Derivative
        return x*(1-x)
    return 1/(1+np.exp(-x)) # Otherwise return 

In [4]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T


In [41]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
np.random.rand(4)

array([  4.17022005e-01,   7.20324493e-01,   1.14374817e-04,
         3.02332573e-01])

In [53]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
syn0

array([[ 0.78921333],
       [-0.82991158],
       [-0.92189043]])

In [50]:
# Iterate through 10,000 Epochs
for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)

Output After Training:
[[ 0.00966651]
 [ 0.0078645 ]
 [ 0.99358978]
 [ 0.99211835]]
