In [148]:
import numpy as np


def sigmoid(x, derive=False):
    if derive == True:
        return x*(1-x)
    return 1 / 1+np.exp(-x)


In [149]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

Y = np.array([[0,0,1,1]]).T


In [150]:
np.random.seed(1)
np.random.rand(4)

array([  4.17022005e-01,   7.20324493e-01,   1.14374817e-04,
         3.02332573e-01])

In [151]:
w_1 = 2*np.random.random((3,1)) - 1
w_1

array([[-0.70648822],
       [-0.81532281],
       [-0.62747958]])

In [152]:
# for x in range(10000):
    
#     l_0 = X
# #     hl_1 = np.dot(l1, w_1.T)

#     l_1 = sigmoid(np.dot(l_0, w_1))
    
#     l1_error = Y - l_1
#     l1_delta = l1_error * sigmoid(l1,True)
#     w_1 += np.dot(l_0, l1_delta)
    
#     print(l_1)
# Iterate through 10,000 Epochs
for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = sigmoid(np.dot(l0,w_1))

    # how much did we miss?
    l1_error = Y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * sigmoid(l1,True)

    # update weights
    w_1 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)

Output After Training:
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
