In [1]:
import numpy as np

In [21]:
class cnn():
    pass

In [2]:
img = np.random.randint(0, 9, size=(7, 7, 3))
np.random.seed(0)
img

array([[[7, 0, 3],
        [4, 6, 2],
        [4, 5, 5],
        [3, 2, 4],
        [7, 0, 3],
        [7, 6, 5],
        [5, 5, 5]],

       [[8, 8, 8],
        [8, 5, 8],
        [3, 5, 4],
        [0, 0, 2],
        [2, 1, 0],
        [4, 0, 2],
        [7, 1, 5]],

       [[7, 7, 7],
        [1, 0, 1],
        [4, 6, 8],
        [7, 0, 8],
        [6, 1, 6],
        [6, 7, 3],
        [4, 1, 6]],

       [[8, 5, 5],
        [1, 3, 7],
        [0, 8, 7],
        [1, 5, 3],
        [6, 1, 4],
        [3, 7, 6],
        [6, 3, 5]],

       [[8, 6, 2],
        [8, 5, 1],
        [6, 8, 6],
        [1, 2, 6],
        [1, 6, 4],
        [7, 8, 4],
        [2, 3, 1]],

       [[4, 0, 6],
        [4, 5, 6],
        [5, 3, 4],
        [6, 8, 6],
        [8, 5, 5],
        [6, 6, 8],
        [4, 5, 1]],

       [[3, 5, 4],
        [1, 6, 0],
        [6, 0, 2],
        [0, 3, 0],
        [1, 4, 8],
        [2, 3, 3],
        [8, 0, 6]]])

In [3]:
# The beginning of each CNN is Convolution
# Input Size of Image = l * w * #channels
# Kernel/Filter = fl * fw * #channels
# Stride = movement 
def convolution(input_Img):
    # One filter accross the same three channels
    filter_1 = np.random.randint(-10, 31, size=(3, 3, 3))
    
    # Read in image
    # Dot product of the image and filter accross all channels
    conv_output = np.dot(input_Img, filter_1)
    # Return the output 
    return conv_output

In [4]:
# Relu 
def relu(input_Img):
    # If value is negative then replace with zero
    np.place(input_Img, input_Img < 0, 0)
    return input_Img

In [ ]:
# (Max) Pooling Layer
def max_pool(feature_map):
    # Pool filter ~ get the max within pfl * pfw * per each channel
    F_spatial = 2
    stride = 2
    
    # Get the current dimensions of the feature map
    length = np.shape(feature_map)[0]
    width = np.shape(feature_map)[1]
    depth = np.shape(feature_map)[2]
    
    # Calculate the dimensions of the max pool filter to be applied
    p_length = (length - F_spatial)/stride + 1
    p_width = (width - F_spatial)/stride + 1
    
    pool_filter = np.zeros((p_length, p_width, depth))
    
    # Iterate through the filter over the current feature map and return a downsized feature map
    for i in range(0, feature_map, 2):
        for j in range(0,0)


In [5]:
img = convolution(img)
img

array([[[[-37,  29, -10],
         [ 59, 137, 140],
         [ 79, 207,  90]],

        [[156,  18,  52],
         [ 54,  28, 252],
         [ 66, 108,  44]],

        [[160,  97,  82],
         [139,  76, 266],
         [ 93, 128,  30]],

        [[ 72,  81,  49],
         [108,  76, 154],
         [ 67, 101,  23]],

        [[-37,  29, -10],
         [ 59, 137, 140],
         [ 79, 207,  90]],

        [[159,  75,  70],
         [129, 109, 336],
         [117, 207,  74]],

        [[150,  90,  75],
         [135,  90, 280],
         [100, 155,  45]]],


       [[[240, 144, 120],
         [216, 144, 448],
         [160, 248,  72]],

        [[153, 147,  93],
         [210, 171, 364],
         [151, 254,  75]],

        [[159,  78,  76],
         [114,  49, 238],
         [ 76,  95,  20]],

        [[ 22,  52,  26],
         [ 58,  26,  28],
         [ 20,  12, -10]],

        [[  9, -15,  -5],
         [ -6,  19,  56],
         [ 17,  52,  29]],

        [[-18,  24,  -2],
         [ 4

In [6]:
img = relu(img)
img

array([[[[  0,  29,   0],
         [ 59, 137, 140],
         [ 79, 207,  90]],

        [[156,  18,  52],
         [ 54,  28, 252],
         [ 66, 108,  44]],

        [[160,  97,  82],
         [139,  76, 266],
         [ 93, 128,  30]],

        [[ 72,  81,  49],
         [108,  76, 154],
         [ 67, 101,  23]],

        [[  0,  29,   0],
         [ 59, 137, 140],
         [ 79, 207,  90]],

        [[159,  75,  70],
         [129, 109, 336],
         [117, 207,  74]],

        [[150,  90,  75],
         [135,  90, 280],
         [100, 155,  45]]],


       [[[240, 144, 120],
         [216, 144, 448],
         [160, 248,  72]],

        [[153, 147,  93],
         [210, 171, 364],
         [151, 254,  75]],

        [[159,  78,  76],
         [114,  49, 238],
         [ 76,  95,  20]],

        [[ 22,  52,  26],
         [ 58,  26,  28],
         [ 20,  12,   0]],

        [[  9,   0,   0],
         [  0,  19,  56],
         [ 17,  52,  29]],

        [[  0,  24,   0],
         [ 4