In [1]:
import numpy as np
from numpy import *

In [2]:
class cnn():
    pass

In [3]:
img = np.random.randint(0, 9, size=(3, 4, 4))
np.random.seed(0)
img

array([[[3, 0, 4, 8],
        [3, 7, 4, 7],
        [2, 2, 0, 0],
        [6, 1, 0, 3]],

       [[6, 6, 0, 3],
        [6, 5, 1, 8],
        [6, 3, 8, 5],
        [1, 1, 4, 5]],

       [[0, 7, 5, 3],
        [2, 2, 2, 3],
        [1, 0, 2, 1],
        [3, 7, 3, 0]]])

In [4]:
# The beginning of each CNN is Convolution
# Input Size of Image = l * w * #channels
# Kernel/Filter = fl * fw * #channels
# Stride = movement 
def convolution(input_Img):
    # One filter accross the same three channels
    filter_1 = np.random.randint(-10, 31, size=(3, np.shape(input_Img[2])[-2],np.shape(input_Img[2])[-1]))
    
    # Read in image
    # Dot product of the image and filter accross all channels
    conv_output = np.dot(input_Img, filter_1)
    # Return the output 
    return conv_output

In [5]:
# Relu 
def relu(input_Img):
    # If value is negative then replace with zero
    np.place(input_Img, input_Img < 0, 0)
    return input_Img

In [9]:
# (Max) Pooling Layer
def max_pool(feature_map):
        # Pool filter ~ get the max within pfl * pfw * per each channel
        F_spatial = 2
        stride = 2

        # Get the current dimensions of the feature map
        depth = np.shape(feature_map)[0]
        length = np.shape(feature_map)[1]
        width = np.shape(feature_map)[2]
        length,width, np.shape(feature_map)

        # Calculate the dimensions of the max pool filter to be applied
        p_length = (length - F_spatial) // stride + 1
        p_width = (width - F_spatial) // stride + 1
        p_length, p_width, depth


        reshape_Dimensions = np.shape(img)
        p_length, p_width, depth, reshape_Dimensions

        # Reshape the Feature Maps
        test = feature_map
        test = test.reshape(depth, p_length, p_length, depth, p_length, p_length)


        max_pool = np.array([],dtype=int)

        for i in range(np.shape(test)[0]):
            for j in range(np.shape(test)[1]):
                # print(test[i][j], 'pass')
                for k in range(np.shape(test)[2]):
                    # print(test[i][j][k],'pass')
                    # Pick the largest value for each channell and add to pool
                    for l in range(np.shape(test)[3]):
                        # print(np.max(test[i][j][k][l]))
                        max_pool = np.append(max_pool, np.max(test[i][j][k][l]))

        # flatten 1D vector of all max values for each channel

        # Reshape the array until a more managable 12 by 3 by 1
        max_pool = np.reshape(max_pool,(12,3, 1))
        #max_pool

        # Each channel is separate into vertical columns
        # Now swap axes and isolated each channel into 1 * n subarrays 
        max_pool = np.swapaxes(test, 0,1)
        #max_pool

        # Reshape into a more comprehensive format for the next convolution
        # Reshape into a n * m * 3
        print("Error: \n", max_pool, "\n", np.shape(max_pool), "\nExpected size:", np.size(max_pool))
        
        max_pool = np.reshape(max_pool,(3,4,3))
        return max_pool

In [7]:
img = convolution(img)
img

array([[[[  38, -109,  259,  375],
         [  -1,  130,  201,  213],
         [ 345,  119,  171,  256]],

        [[  29,  -37,  308,  528],
         [ 114,  143,  162,  192],
         [ 523,  272,   90,  225]],

        [[ -22,    4,    8,  110],
         [  56,   34,   10,   52],
         [  96,   62,    0,    6]],

        [[ -55,  -60,   53,  287],
         [  63,  111,  115,  203],
         [ 218,   79,   99,   95]]],


       [[[ -60,  -15,  108,  417],
         [ 138,  126,  105,  198],
         [ 363,  189,   54,   90]],

        [[ -36,  -73,  251,  550],
         [  83,  169,  227,  274],
         [ 481,  193,  153,  224]],

        [[  51,  -92,  243,  509],
         [ 153,  181,  121,  269],
         [ 502,  293,  117,  245]],

        [[  51,  -59,  200,  256],
         [  18,   81,  110,  116],
         [ 261,  120,   90,  175]]],


       [[[  64,   16,  231,  339],
         [ 125,   75,   36,   60],
         [ 388,  262,   -9,  130]],

        [[  10,  -31,  120,  225]

In [8]:
img = relu(img)
print(img[0][:])
img = max_pool(img)

[[[ 38   0 259 375]
  [  0 130 201 213]
  [345 119 171 256]]

 [[ 29   0 308 528]
  [114 143 162 192]
  [523 272  90 225]]

 [[  0   4   8 110]
  [ 56  34  10  52]
  [ 96  62   0   6]]

 [[  0   0  53 287]
  [ 63 111 115 203]
  [218  79  99  95]]]
Error: 
 [[[[[[ 38   0]
     [259 375]]

    [[  0 130]
     [201 213]]

    [[345 119]
     [171 256]]]


   [[[ 29   0]
     [308 528]]

    [[114 143]
     [162 192]]

    [[523 272]
     [ 90 225]]]]



  [[[[  0   0]
     [108 417]]

    [[138 126]
     [105 198]]

    [[363 189]
     [ 54  90]]]


   [[[  0   0]
     [251 550]]

    [[ 83 169]
     [227 274]]

    [[481 193]
     [153 224]]]]



  [[[[ 64  16]
     [231 339]]

    [[125  75]
     [ 36  60]]

    [[388 262]
     [  0 130]]]


   [[[ 10   0]
     [120 225]]

    [[ 46  70]
     [ 75 104]]

    [[215 107]
     [ 54 104]]]]]




 [[[[[  0   4]
     [  8 110]]

    [[ 56  34]
     [ 10  52]]

    [[ 96  62]
     [  0   6]]]


   [[[  0   0]
     [ 53 287]]

    [[ 63 111]
  

ValueError: total size of new array must be unchanged

In [ ]:
img

feature_map = img

#         # Pool filter ~ get the max within pfl * pfw * per each channel
#         F_spatial = 2
#         stride = 2

#         # Get the current dimensions of the feature map
#         depth = np.shape(feature_map)[0]
#         length = np.shape(feature_map)[1]
#         width = np.shape(feature_map)[2]
#         length,width, np.shape(feature_map)

#         # Calculate the dimensions of the max pool filter to be applied
#         p_length = (length - F_spatial) // stride + 1
#         p_width = (width - F_spatial) // stride + 1
#         p_length, p_width, depth


#         reshape_Dimensions = np.shape(img)
#         p_length, p_width, depth, reshape_Dimensions

# #         # Reshape the Feature Maps
# #         test = feature_map
# #         test = test.reshape(depth, p_length, p_length, depth, p_length, p_length)
# #         test
# #         # np.size(test) // (4*4*3)

# #         test[0][0][0][0]

# #         np.shape(test)

#         max_pool = np.array([],dtype=int)

#         for i in range(np.shape(test)[0]):
#             for j in range(np.shape(test)[1]):
#         #         print(test[i][j], 'pass')
#                 for k in range(np.shape(test)[2]):
#         #             print(test[i][j][k],'pass')
#                     # Pick the largest value for each channell and add to pool
#                     for l in range(np.shape(test)[3]):
#                         print(np.max(test[i][j][k][l]))
#                         max_pool = np.append(max_pool, np.max(test[i][j][k][l]))

#         # flatten 1D vector of all max values for each channel
#         max_pool

#         # Reshape the array until a more managable 12 by 3 by 1
#         max_pool = np.reshape(max_pool,(12,3, 1))
#         max_pool

#         # Each channel is separate into vertical columns
#         # Now swap axes and isolated each channel into 1 * n subarrays 
#         max_pool = np.swapaxes(test, 0,1)
#         max_pool

#         # Reshape into a more comprehensive format for the next convolution
#         # Reshape into a n * m * 3
#         max_pool = np.reshape(max_pool,(3,4,3))
#         max_pool
